services:
  powerguardian-connector:
    image: ghcr.io/powerguardianos/connectoros-docker:latest
    container_name: powerguardian-connector
    network_mode: host
    privileged: true
    volumes:
      - ./data:/data
      - nut-etc:/etc/nut
      - nut-run:/var/run/nut
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - PG_DATA_DIR=/data
      - PG_AGENT_KEY=
    extra_hosts:
      - "powerguardian.local:10.0.0.40"
    restart: unless-stopped

volumes:
  nut-etc:
  nut-run:
